GUI cleanup
hpcbot/hpcbot pull request #73
Opened 2017-08-21 18:55 UTC by LarryManalo

Soundboard buttons now use classes.
Padding on buttons has been increased.
Buttons are listed alphabetically.

2017-08-21 23:00 UTC, bdickason commented
I don't have time to pull this down and test but can you provide a screen shot so I can take a look?

2017-08-21 23:05 UTC, bdickason requested changes
Put in-line comments with some changes before approving

2017-08-21 23:05 UTC, bdickason commented on lib/twitch-soundboard/views/index.pug
> +		<fieldset class="divider1">
Can you convert Legend and Fieldset tags to PUG format instead of HTML?

e.g. 
legend.title1
fieldset.divider1

2017-08-21 23:05 UTC, bdickason commented on lib/twitch-soundboard/static/css/soundboard.css
>  button#gift {
Can you consolidate the button styling to a class or apply it to the specific button tag? It looks like they're all the same.

2017-08-21 23:05 UTC, bdickason commented on lib/twitch-soundboard/static/css/soundboard.css
> +.divider1 {
Do we need the '1' here? It doesn't look like there are other dividers or titles and I can't see why we'd need more than one instance of future dividers or titles.

2017-08-22 01:15 UTC, bdickason commented on lib/twitch-soundboard/static/css/soundboard.css
>  button#gift {
I would do something like:
css:
button {
background-color: blue;
color: white;
width: 100%;
padding: 5px 10px;
font-size: 16px;
}

PUG:
button#muggle

2017-08-22 01:16 UTC, bdickason commented on lib/twitch-soundboard/static/css/soundboard.css
>  button#gift {
so you apply the CSS style to the html tag 'button' itself, then you add the id to each button inthe PUG file (which I think we already do).

2017-08-22 05:08 UTC, closed without merging

2017-08-22 05:08 UTC, LarryManalo commented
Closing to make changes.